// Teksten die niet in de ontwerpversie stonden. Zelfde sleutelopzet als content/dict.json.
export const extra = {
  nl: {
    taalNaam: "Nederlands", mailAntwoordOnderwerp: "Antwoord op uw vraag bij {doc}", mailAntwoordKop: "U heeft antwoord op uw vraag", mailBekijk: "Bekijk het gesprek", mailOntvangenOnderwerp: "Wij hebben uw aanvraag ontvangen (offerte {nr})", mailOntvangenKop: "Uw aanvraag is ontvangen", mailOntvangenTekst: "Bedankt. Wij maken offerte {nr} voor u en laten het u weten. U ziet de status ook in Mijn omgeving.", stGereserveerd: "Gereserveerd", stVerlopen: "Verlopen", stOfferte: "Offerte verstuurd", stAkkoord: "Akkoord gegeven, wordt een order", stGeannuleerd: "Geannuleerd", fotoVolgt: "Foto volgt", deelWa: "Deel via WhatsApp", menu: "Menu", naarInhoud: "Naar de inhoud",
    loginTitel: "Inloggen", loginVerstuurd: "Controleer je mail. We hebben een inloglink gestuurd naar {email}. Open de link op dit apparaat.", loginFout: "De inloglink kon niet worden verstuurd. Controleer het e-mailadres en probeer het zo nog eens.",
    loginNog: "Nog geen klant?", loginNogLink: "Meld je aan",
    stAangevraagd: "Je aanmelding wordt gecontroleerd. Zodra je account is goedgekeurd zie je de prijzen en kun je offertes aanvragen. Je hoort van ons.",
    stGeblokkeerd: "Dit account heeft op dit moment geen toegang. Neem contact met ons op als je denkt dat dit niet klopt.",
    stOnbekend: "Dit e-mailadres is nog niet bij ons bekend. Meld je aan als zakelijke klant, dan controleren we je gegevens.",
    stUitgelogd: "Je bent niet ingelogd.",
    spamFout: "De spamcontrole is mislukt. Laad de pagina opnieuw en probeer het nog eens.", teVaak: "Je hebt dit te vaak gedaan. Probeer het later opnieuw.", algFout: "Er ging iets mis. Probeer het zo nog eens, of mail ons.",
    akkoordNodig: "Ga akkoord met de voorwaarden en het privacybeleid om door te gaan.",
    verzenden: "Verzenden", bericht: "Bericht", contactTitel: "Neem contact op", contactOk: "Bedankt voor je bericht. We reageren zo snel mogelijk.",
    openingstijden: "Openingstijden", maVr: "Ma–vr", za: "Za", zo: "Zo", opAfspraak: "Op afspraak", gesloten: "Gesloten",
    adresL: "Adres", postcodeL: "Postcode", plaatsL: "Plaats", brancheL: "Soort bedrijf",
    br_detailhandel: "Winkel (detailhandel)", br_webshop: "Webshop", br_groothandel: "Groothandel", br_horeca: "Horeca", br_overig: "Anders",
    kvkOfBtw: "Vul je KvK-nummer of btw-nummer in.", gegevensNodig: "Vul de verplichte velden in.", mailOngeldig: "Dit is geen geldig e-mailadres.", kiesCat: "Kies minstens één categorie.",
    klantTitel: "Klant worden", klantStap: "Na je aanmelding controleren we je gegevens. Je krijgt bericht zodra je prijzen kunt zien.",
    aanbiedenOk: "Bedankt. We bekijken je aanbod en reageren binnen 48 uur.", omschrijvingL: "Wat voor partij? (artikelen, aantallen, pallets, locatie)", hoeveelheidL: "Hoeveelheid", prijsideeL: "Prijsidee (optioneel)", linkL: "Link naar foto’s of lijst (optioneel)", telefoonL: "Telefoon (optioneel)",
    alertTitel: "Handel alert", alertWelke: "Over welke categorieën wil je een mail?", alertOk: "Aangemeld. Je krijgt een mail bij nieuwe partijen in de gekozen categorieën.", alertKies: "Kies minstens één categorie.",
    prijsExcl: "Alle prijzen zijn in euro, excl. btw.", opVoorraad: "Op voorraad", stuksPerOmdoos: "stuks per omdoos", stuksPerPallet: "stuks per pallet", ean: "EAN", loginVoorPrijs: "Log in voor de prijs", artikelNiet: "Dit artikel is voor jouw land niet beschikbaar.", artikelLogin: "Dit artikel is alleen zichtbaar voor ingelogde klanten.",
    geenResultaat: "Niets gevonden voor deze keuze.", vorige: "Vorige", volgende: "Volgende", pagina: "Pagina", van: "van", zoekOpdracht: "Zoekopdracht",
    bodLabel: "Jouw bod voor de hele partij (totaalbedrag, excl. btw)", bodToelichting: "Je neemt de volledige voorraad af. Noem het totaalbedrag dat je wilt bieden; wij reageren binnen 48 uur.", bodAanvullend: "Opmerking (optioneel)", bodNodig: "Vul een bedrag in.", bodFout: "Het bod kon niet worden geplaatst. Controleer het bedrag en probeer het nog eens.",
    offerteLijstTitel: "Je offertelijst", offerteLeegP: "Zet artikelen op je offertelijst en vraag in één keer een offerte aan.", verwijder: "Verwijder", aantalOmdozen: "Omdozen", stuksTotaal: "Stuks", naarPartijen: "Bekijk de partijen",
    afhalenKiezen: "Afhalen of bezorgen?", afhaalDatum: "Gewenste afhaaldatum (optioneel)", opmerkingL: "Opmerking (optioneel)", landL: "Land", aanvraagOk: "Bedankt. Je aanvraag staat bij ons klaar. Offertenummer {nummer}. Je krijgt de offerte per mail; je ziet hem ook onder Mijn omgeving.",
    aanvraagFout: "De aanvraag kon niet worden verstuurd.", fout_geen_toegang: "Je bent niet ingelogd, of je account heeft geen toegang.", fout_niet_beschikbaar: "Een van de artikelen is niet meer beschikbaar. Haal het van je lijst en probeer opnieuw.", fout_te_weinig_voorraad: "Van een van de artikelen is niet genoeg voorraad. Verlaag het aantal omdozen en probeer opnieuw.",
    inloggenVoorOfferte: "Log in om een offerte aan te vragen.", beperkingLand: "Niet alle artikelen zijn in elk land verkrijgbaar. Wat voor jou niet kan, zie je niet op de site.",
    mijnOverzicht: "Overzicht", mijnOpenstaand: "Openstaand", mijnOffertes: "Offertes", mijnOrders: "Orders", mijnBerichten: "Berichten", mijnGegevens: "Gegevens",
    nogOpenstaand: "Openstaand bedrag", factuur: "Factuur", vervaldatum: "Vervaldatum", teLaat: "Te laat", nietsOpenstaand: "Er staat niets open.", rest: "Openstaand",
    offerteNr: "Offerte {nr}", orderNr: "Order {nr}", status: "Status", totaalExcl: "Totaal excl. btw", geenRegels: "Geen regels.", omschrijving: "Omschrijving", aantal: "Aantal", prijs: "Prijs", bedrag: "Bedrag",
    akkoordToelichting: "Ga je akkoord met deze offerte? Dan maken wij er een order van.", akkoordNaamL: "Je naam, ter bevestiging", akkoordKnop: "Akkoord, maak er een order van", akkoordGegeven: "Je akkoord is ontvangen op {datum}. Wij maken er een order van.", akkoordOkMsg: "Bedankt voor je akkoord. Wij maken er een order van en laten het je weten.", akkoordFout: "Het akkoord kon niet worden verstuurd. Is de offerte nog geldig?",
    bodStatus: "Bod op de hele partij", bodBedrag: "Jouw bod", zendingen: "Verzending en afhalen", vervoerder: "Vervoerder", trackTrace: "Track & trace", pallets: "Pallets", colli: "Colli", gepland: "Gepland op", afhaaltijd: "Afhaaltijd",
    berichtVerstuurd: "Bericht verstuurd.", berichtFout: "Het bericht kon niet worden verstuurd.", berichtLeeg: "Typ eerst een bericht.", gesprekken: "Gesprekken", geenGesprekken: "Nog geen offertes of orders om een gesprek bij te voeren.",
    gegevensOpgeslagen: "Opgeslagen.", gegevensFout: "Opslaan lukte niet.", contactpersoonL: "Contactpersoon", taalL: "Taal", gegevensNota: "Wil je je bedrijfsnaam, adres of btw-nummer laten wijzigen? Stuur ons een bericht via Contact.",
    uitloggen: "Uitloggen", ingelogdAls: "Ingelogd als {email}", welkomNaam: "Welkom, {naam}",
    paginaNietGevonden: "Deze pagina bestaat niet (meer).", terugNaarHome: "Terug naar de homepage", partijNietMeer: "Deze partij is niet meer beschikbaar.", bekijkAnder: "Bekijk de partijen die nu op voorraad zijn.",
    agendaLeeg: "Er staan op dit moment geen beurzen of bijzondere dagen in de agenda.", agendaTot: "t/m",
    footerAdres: "Rheastraat 19, 5047 TL Tilburg", cookieNoot: "Deze site gebruikt alleen functionele cookies (inloggen). Geen tracking.",
    wijzig: "Wijzigen", opslaanKnop: "Opslaan", sluit: "Sluiten", meer: "Meer", selecteer: "Kies",
    metaHome: "Restpartijen, overstock en faillissementspartijen voor zakelijke kopers, uit ons eigen magazijn in Tilburg. Minimale afname 1 omdoos.", metaPartijen: "Alle partijen op voorraad: restpartijen en overstock voor wederverkopers. Prijzen na inloggen.",
  },
  en: {
    taalNaam: "English", mailAntwoordOnderwerp: "Reply to your question about {doc}", mailAntwoordKop: "You have a reply to your question", mailBekijk: "View the conversation", mailOntvangenOnderwerp: "We received your request (quote {nr})", mailOntvangenKop: "Your request was received", mailOntvangenTekst: "Thank you. We are preparing quote {nr} for you and will let you know. You can also follow the status under My account.", stGereserveerd: "Reserved", stVerlopen: "Expired", stOfferte: "Quote sent", stAkkoord: "Approved, becoming an order", stGeannuleerd: "Cancelled", fotoVolgt: "Photo to follow", deelWa: "Share via WhatsApp", menu: "Menu", naarInhoud: "Skip to content",
    loginTitel: "Log in", loginVerstuurd: "Check your email. We sent a login link to {email}. Open the link on this device.", loginFout: "The login link could not be sent. Check the email address and try again in a moment.",
    loginNog: "Not a customer yet?", loginNogLink: "Register",
    stAangevraagd: "Your registration is being checked. Once your account is approved you will see prices and can request quotes. We will let you know.",
    stGeblokkeerd: "This account has no access at the moment. Contact us if you think this is wrong.",
    stOnbekend: "We do not know this email address yet. Register as a business customer and we will check your details.",
    stUitgelogd: "You are not logged in.",
    spamFout: "The spam check failed. Reload the page and try again.", teVaak: "You did this too often. Please try again later.", algFout: "Something went wrong. Try again in a moment, or email us.",
    akkoordNodig: "Agree to the terms and the privacy policy to continue.",
    verzenden: "Send", bericht: "Message", contactTitel: "Get in touch", contactOk: "Thank you for your message. We will reply as soon as possible.",
    openingstijden: "Opening hours", maVr: "Mon–Fri", za: "Sat", zo: "Sun", opAfspraak: "By appointment", gesloten: "Closed",
    adresL: "Address", postcodeL: "Postcode", plaatsL: "City", brancheL: "Type of business",
    br_detailhandel: "Shop (retail)", br_webshop: "Webshop", br_groothandel: "Wholesale", br_horeca: "Hospitality", br_overig: "Other",
    kvkOfBtw: "Enter your Chamber of Commerce number or VAT number.", gegevensNodig: "Fill in the required fields.", mailOngeldig: "This is not a valid email address.", kiesCat: "Choose at least one category.",
    klantTitel: "Become a customer", klantStap: "After you register we check your details. You will hear from us as soon as you can see prices.",
    aanbiedenOk: "Thank you. We will look at your offer and reply within 48 hours.", omschrijvingL: "What kind of lot? (items, quantities, pallets, location)", hoeveelheidL: "Quantity", prijsideeL: "Price idea (optional)", linkL: "Link to photos or list (optional)", telefoonL: "Phone (optional)",
    alertTitel: "Trade alert", alertWelke: "Which categories do you want to hear about?", alertOk: "Signed up. You will get an email when new lots arrive in the chosen categories.", alertKies: "Choose at least one category.",
    prijsExcl: "All prices are in euro, excl. VAT.", opVoorraad: "In stock", stuksPerOmdoos: "pieces per outer box", stuksPerPallet: "pieces per pallet", ean: "EAN", loginVoorPrijs: "Log in for the price", artikelNiet: "This item is not available for your country.", artikelLogin: "This item is only visible to logged-in customers.",
    geenResultaat: "Nothing found for this selection.", vorige: "Previous", volgende: "Next", pagina: "Page", van: "of", zoekOpdracht: "Search",
    bodLabel: "Your bid for the entire lot (total amount, excl. VAT)", bodToelichting: "You take the complete stock. State the total amount you want to bid; we reply within 48 hours.", bodAanvullend: "Remarks (optional)", bodNodig: "Enter an amount.", bodFout: "The bid could not be placed. Check the amount and try again.",
    offerteLijstTitel: "Your quote list", offerteLeegP: "Add items to your quote list and request a quote in one go.", verwijder: "Remove", aantalOmdozen: "Outer boxes", stuksTotaal: "Pieces", naarPartijen: "View the lots",
    afhalenKiezen: "Collect or deliver?", afhaalDatum: "Preferred collection date (optional)", opmerkingL: "Remarks (optional)", landL: "Country", aanvraagOk: "Thank you. Your request is with us. Quote number {nummer}. You will receive the quote by email; you can also see it under My account.",
    aanvraagFout: "The request could not be sent.", fout_geen_toegang: "You are not logged in, or your account has no access.", fout_niet_beschikbaar: "One of the items is no longer available. Remove it from your list and try again.", fout_te_weinig_voorraad: "There is not enough stock of one of the items. Lower the number of outer boxes and try again.",
    inloggenVoorOfferte: "Log in to request a quote.", beperkingLand: "Not every item is available in every country. What is not possible for you is not shown on the site.",
    mijnOverzicht: "Overview", mijnOpenstaand: "Open items", mijnOffertes: "Quotes", mijnOrders: "Orders", mijnBerichten: "Messages", mijnGegevens: "Details",
    nogOpenstaand: "Amount outstanding", factuur: "Invoice", vervaldatum: "Due date", teLaat: "Overdue", nietsOpenstaand: "Nothing is open.", rest: "Outstanding",
    offerteNr: "Quote {nr}", orderNr: "Order {nr}", status: "Status", totaalExcl: "Total excl. VAT", geenRegels: "No lines.", omschrijving: "Description", aantal: "Quantity", prijs: "Price", bedrag: "Amount",
    akkoordToelichting: "Do you approve this quote? Then we turn it into an order.", akkoordNaamL: "Your name, as confirmation", akkoordKnop: "Approve, turn into order", akkoordGegeven: "Your approval was received on {datum}. We are turning it into an order.", akkoordOkMsg: "Thank you for your approval. We are turning it into an order and will let you know.", akkoordFout: "The approval could not be sent. Is the quote still valid?",
    bodStatus: "Bid on the entire lot", bodBedrag: "Your bid", zendingen: "Shipping and collection", vervoerder: "Carrier", trackTrace: "Track & trace", pallets: "Pallets", colli: "Parcels", gepland: "Planned on", afhaaltijd: "Collection time",
    berichtVerstuurd: "Message sent.", berichtFout: "The message could not be sent.", berichtLeeg: "Type a message first.", gesprekken: "Conversations", geenGesprekken: "No quotes or orders yet to hold a conversation about.",
    gegevensOpgeslagen: "Saved.", gegevensFout: "Saving failed.", contactpersoonL: "Contact person", taalL: "Language", gegevensNota: "Want to change your company name, address or VAT number? Send us a message via Contact.",
    uitloggen: "Log out", ingelogdAls: "Logged in as {email}", welkomNaam: "Welcome, {naam}",
    paginaNietGevonden: "This page does not exist (anymore).", terugNaarHome: "Back to the homepage", partijNietMeer: "This lot is no longer available.", bekijkAnder: "View the lots that are in stock now.",
    agendaLeeg: "There are no fairs or special days in the agenda at the moment.", agendaTot: "to",
    footerAdres: "Rheastraat 19, 5047 TL Tilburg, the Netherlands", cookieNoot: "This site only uses functional cookies (login). No tracking.",
    wijzig: "Change", opslaanKnop: "Save", sluit: "Close", meer: "More", selecteer: "Choose",
    metaHome: "Surplus, overstock and liquidation lots for business buyers, from our own warehouse in Tilburg. Minimum order 1 outer box.", metaPartijen: "All lots in stock: surplus and overstock for resellers. Prices after login.",
  },
  de: {
    taalNaam: "Deutsch", mailAntwoordOnderwerp: "Antwort auf Ihre Frage zu {doc}", mailAntwoordKop: "Sie haben eine Antwort auf Ihre Frage", mailBekijk: "Gespräch ansehen", mailOntvangenOnderwerp: "Wir haben Ihre Anfrage erhalten (Angebot {nr})", mailOntvangenKop: "Ihre Anfrage ist eingegangen", mailOntvangenTekst: "Danke. Wir erstellen Angebot {nr} für Sie und melden uns. Den Status sehen Sie auch unter Mein Bereich.", stGereserveerd: "Reserviert", stVerlopen: "Abgelaufen", stOfferte: "Angebot gesendet", stAkkoord: "Zugestimmt, wird ein Auftrag", stGeannuleerd: "Storniert", fotoVolgt: "Foto folgt", deelWa: "Per WhatsApp teilen", menu: "Menü", naarInhoud: "Zum Inhalt",
    loginTitel: "Anmelden", loginVerstuurd: "Prüfen Sie Ihre E-Mail. Wir haben einen Anmeldelink an {email} gesendet. Öffnen Sie den Link auf diesem Gerät.", loginFout: "Der Anmeldelink konnte nicht gesendet werden. Prüfen Sie die E-Mail-Adresse und versuchen Sie es gleich noch einmal.",
    loginNog: "Noch kein Kunde?", loginNogLink: "Registrieren",
    stAangevraagd: "Ihre Anmeldung wird geprüft. Sobald Ihr Konto freigegeben ist, sehen Sie die Preise und können Angebote anfragen. Wir melden uns.",
    stGeblokkeerd: "Dieses Konto hat derzeit keinen Zugang. Kontaktieren Sie uns, wenn Sie meinen, dass das nicht stimmt.",
    stOnbekend: "Diese E-Mail-Adresse ist uns noch nicht bekannt. Registrieren Sie sich als Geschäftskunde, dann prüfen wir Ihre Angaben.",
    stUitgelogd: "Sie sind nicht angemeldet.",
    spamFout: "Die Spam-Prüfung ist fehlgeschlagen. Laden Sie die Seite neu und versuchen Sie es erneut.", teVaak: "Sie haben das zu oft getan. Bitte versuchen Sie es später erneut.", algFout: "Etwas ist schiefgegangen. Versuchen Sie es gleich noch einmal oder mailen Sie uns.",
    akkoordNodig: "Stimmen Sie den AGB und der Datenschutzerklärung zu, um fortzufahren.",
    verzenden: "Senden", bericht: "Nachricht", contactTitel: "Kontakt aufnehmen", contactOk: "Danke für Ihre Nachricht. Wir antworten so schnell wie möglich.",
    openingstijden: "Öffnungszeiten", maVr: "Mo–Fr", za: "Sa", zo: "So", opAfspraak: "Nach Vereinbarung", gesloten: "Geschlossen",
    adresL: "Adresse", postcodeL: "Postleitzahl", plaatsL: "Ort", brancheL: "Art des Unternehmens",
    br_detailhandel: "Geschäft (Einzelhandel)", br_webshop: "Webshop", br_groothandel: "Großhandel", br_horeca: "Gastronomie", br_overig: "Sonstiges",
    kvkOfBtw: "Geben Sie Ihre KvK-Nummer oder USt-IdNr. an.", gegevensNodig: "Füllen Sie die Pflichtfelder aus.", mailOngeldig: "Das ist keine gültige E-Mail-Adresse.", kiesCat: "Wählen Sie mindestens eine Kategorie.",
    klantTitel: "Kunde werden", klantStap: "Nach der Anmeldung prüfen wir Ihre Angaben. Sie hören von uns, sobald Sie Preise sehen können.",
    aanbiedenOk: "Danke. Wir sehen uns Ihr Angebot an und antworten innerhalb von 48 Stunden.", omschrijvingL: "Was für ein Posten? (Artikel, Mengen, Paletten, Standort)", hoeveelheidL: "Menge", prijsideeL: "Preisvorstellung (optional)", linkL: "Link zu Fotos oder Liste (optional)", telefoonL: "Telefon (optional)",
    alertTitel: "Handel-Alert", alertWelke: "Zu welchen Kategorien möchten Sie eine E-Mail?", alertOk: "Angemeldet. Sie erhalten eine E-Mail bei neuen Posten in den gewählten Kategorien.", alertKies: "Wählen Sie mindestens eine Kategorie.",
    prijsExcl: "Alle Preise in Euro, zzgl. MwSt.", opVoorraad: "Auf Lager", stuksPerOmdoos: "Stück pro Umkarton", stuksPerPallet: "Stück pro Palette", ean: "EAN", loginVoorPrijs: "Anmelden für den Preis", artikelNiet: "Dieser Artikel ist für Ihr Land nicht verfügbar.", artikelLogin: "Dieser Artikel ist nur für angemeldete Kunden sichtbar.",
    geenResultaat: "Für diese Auswahl wurde nichts gefunden.", vorige: "Zurück", volgende: "Weiter", pagina: "Seite", van: "von", zoekOpdracht: "Suche",
    bodLabel: "Ihr Gebot für den gesamten Posten (Gesamtbetrag, zzgl. MwSt.)", bodToelichting: "Sie nehmen den gesamten Bestand ab. Nennen Sie den Gesamtbetrag, den Sie bieten möchten; wir antworten innerhalb von 48 Stunden.", bodAanvullend: "Anmerkung (optional)", bodNodig: "Geben Sie einen Betrag ein.", bodFout: "Das Gebot konnte nicht abgegeben werden. Prüfen Sie den Betrag und versuchen Sie es erneut.",
    offerteLijstTitel: "Ihre Angebotsliste", offerteLeegP: "Setzen Sie Artikel auf Ihre Angebotsliste und fragen Sie in einem Schritt ein Angebot an.", verwijder: "Entfernen", aantalOmdozen: "Umkartons", stuksTotaal: "Stück", naarPartijen: "Posten ansehen",
    afhalenKiezen: "Abholen oder liefern?", afhaalDatum: "Gewünschtes Abholdatum (optional)", opmerkingL: "Anmerkung (optional)", landL: "Land", aanvraagOk: "Danke. Ihre Anfrage liegt bei uns vor. Angebotsnummer {nummer}. Sie erhalten das Angebot per E-Mail; Sie sehen es auch unter Mein Bereich.",
    aanvraagFout: "Die Anfrage konnte nicht gesendet werden.", fout_geen_toegang: "Sie sind nicht angemeldet, oder Ihr Konto hat keinen Zugang.", fout_niet_beschikbaar: "Einer der Artikel ist nicht mehr verfügbar. Entfernen Sie ihn von Ihrer Liste und versuchen Sie es erneut.", fout_te_weinig_voorraad: "Von einem der Artikel ist nicht genug auf Lager. Verringern Sie die Anzahl der Umkartons und versuchen Sie es erneut.",
    inloggenVoorOfferte: "Melden Sie sich an, um ein Angebot anzufragen.", beperkingLand: "Nicht jeder Artikel ist in jedem Land erhältlich. Was für Sie nicht möglich ist, sehen Sie auf der Seite nicht.",
    mijnOverzicht: "Übersicht", mijnOpenstaand: "Offene Posten", mijnOffertes: "Angebote", mijnOrders: "Aufträge", mijnBerichten: "Nachrichten", mijnGegevens: "Daten",
    nogOpenstaand: "Offener Betrag", factuur: "Rechnung", vervaldatum: "Fälligkeit", teLaat: "Überfällig", nietsOpenstaand: "Nichts offen.", rest: "Offen",
    offerteNr: "Angebot {nr}", orderNr: "Auftrag {nr}", status: "Status", totaalExcl: "Gesamt zzgl. MwSt.", geenRegels: "Keine Positionen.", omschrijving: "Beschreibung", aantal: "Menge", prijs: "Preis", bedrag: "Betrag",
    akkoordToelichting: "Sind Sie mit diesem Angebot einverstanden? Dann machen wir daraus einen Auftrag.", akkoordNaamL: "Ihr Name, zur Bestätigung", akkoordKnop: "Einverstanden, Auftrag erteilen", akkoordGegeven: "Ihre Zustimmung ging am {datum} bei uns ein. Wir machen einen Auftrag daraus.", akkoordOkMsg: "Danke für Ihre Zustimmung. Wir machen einen Auftrag daraus und melden uns.", akkoordFout: "Die Zustimmung konnte nicht gesendet werden. Ist das Angebot noch gültig?",
    bodStatus: "Gebot auf den gesamten Posten", bodBedrag: "Ihr Gebot", zendingen: "Versand und Abholung", vervoerder: "Spediteur", trackTrace: "Sendungsverfolgung", pallets: "Paletten", colli: "Colli", gepland: "Geplant am", afhaaltijd: "Abholzeit",
    berichtVerstuurd: "Nachricht gesendet.", berichtFout: "Die Nachricht konnte nicht gesendet werden.", berichtLeeg: "Schreiben Sie zuerst eine Nachricht.", gesprekken: "Gespräche", geenGesprekken: "Noch keine Angebote oder Aufträge für ein Gespräch.",
    gegevensOpgeslagen: "Gespeichert.", gegevensFout: "Speichern fehlgeschlagen.", contactpersoonL: "Ansprechpartner", taalL: "Sprache", gegevensNota: "Möchten Sie Firmenname, Adresse oder USt-IdNr. ändern lassen? Schreiben Sie uns über Kontakt.",
    uitloggen: "Abmelden", ingelogdAls: "Angemeldet als {email}", welkomNaam: "Willkommen, {naam}",
    paginaNietGevonden: "Diese Seite existiert (nicht mehr).", terugNaarHome: "Zurück zur Startseite", partijNietMeer: "Dieser Posten ist nicht mehr verfügbar.", bekijkAnder: "Sehen Sie sich die Posten an, die jetzt auf Lager sind.",
    agendaLeeg: "Derzeit stehen keine Messen oder besonderen Tage im Kalender.", agendaTot: "bis",
    footerAdres: "Rheastraat 19, 5047 TL Tilburg, Niederlande", cookieNoot: "Diese Seite verwendet nur funktionale Cookies (Anmeldung). Kein Tracking.",
    wijzig: "Ändern", opslaanKnop: "Speichern", sluit: "Schließen", meer: "Mehr", selecteer: "Wählen",
    metaHome: "Restposten, Überbestände und Insolvenzposten für gewerbliche Käufer, aus unserem eigenen Lager in Tilburg. Mindestabnahme 1 Umkarton.", metaPartijen: "Alle Posten auf Lager: Restposten und Überbestände für Wiederverkäufer. Preise nach der Anmeldung.",
  },
} as const;
